### ISSUE TITLE
Keybindings don't seem to be working!

### ISSUE THREAD

**Issue by AvijeetPrasad** [vipzhicheng/logseq-plugin-task-management-shortcuts#1]
Hi, 

I tried the default keybindings and also after changing the plugin settings, I tried the alternative one suggested in the ReadMe. I am not able to get the plugin to work. I am surprised, because it used to work fine few months ago, when I had last tried it.
Can you please have a look?

The following are the system settings:

Laptop: macOS 12.6 (M1 chip)
Logseq: version 0.8.7
plugin: v0.0.2

**Comment by vipzhicheng** [comment]
The plugin works on my local, I tried to reinstall the marketplace version it also works. Please confirm this issue on the v0.8.8+ to check if this issue still exists.

**Comment by AvijeetPrasad** [comment]
Hi, Thanks for looking in to it. After checking the keyword shortcuts, I realized that there was a conflict with shortcuts for switching to different desktops (probably Mac defaults). So, I unchecked them. Now everything is working as expected 👍🏼 
 
![Screenshot 2022-10-14 at 09 01 26](https://user-images.githubusercontent.com/45669486/195783115-e231e745-c5e9-4baa-b6c4-4ff6a27b7695.jpg)
